version: "3.7"

x-deploy: &template-deploy
  replicas: 1
  restart_policy:
    condition: on-failure
  update_config:
    parallelism: 1
    delay: 10s
services:
  zabbix-server:
    image: zabbix/zabbix-server-mysql:centos-5.0.2
    env_file: 
      - ./envs/zabbix-server/common.env
    networks:
      - "monitoring-network"
    volumes:
        - ./data_internal/zabbix-server/externalscripts:/usr/lib/zabbix/externalscripts
        - ./data_internal/zabbix-server/alertscripts:/usr/lib/zabbix/alertscripts
    ports:
      - "10051:10051"
    deploy: *template-deploy
  zabbix-frontend:
    image: zabbix/zabbix-web-nginx-mysql:alpine-5.0.2
    env_file: 
      - ./envs/zabbix-frontend/common.env
    ports:
      - "80:8080"
    networks:
      - "monitoring-network"
    deploy: *template-deploy

networks: 
  monitoring-network:
    external: true